import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { Main } from '../components/Main'
import { stripe } from '../services/stripe'

interface HomeProps {
  product: {
    priceId: string;
    amount: number;
  }
}

const Home = ( {product} : HomeProps) => {
  const {amount} = product
  return (
    <div>
      <Head>
        <title>DevFront</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen">
        <Main price={amount}/>
      </div>
    </div>
  )
}

export default Home;

export const getServerSideProps : GetServerSideProps = async () => {
  const price = await stripe.prices.retrieve('price_1LAEfpIMTDPlIEvmZ1v0ODL8', {
    expand: ['product']
  })

  const product = {
    priceId: price.id,
    amount: price.unit_amount
  }

  return {
    props: {
      product
    }
  }
}